# Generated by Django 3.2.6 on 2021-08-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='caffeine_mg',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_fluid_ounce',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='size_ml',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
